<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="SuratUmroh_files/filelist.xml">
<style id="Surat Pernyataan 2_23148_Styles">
<!--table
  {mso-displayed-decimal-separator:"\.";
  mso-displayed-thousand-separator:"\,";}
.xl1523148
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:11.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:general;
  vertical-align:bottom;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
.xl6323148
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:12.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:general;
  vertical-align:bottom;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
.xl6423148
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:11.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:center;
  vertical-align:bottom;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
.xl6523148
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:16.0pt;
  font-weight:700;
  font-style:normal;
  text-decoration:underline;
  text-underline-style:single;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:center;
  vertical-align:bottom;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
.xl6623148
  {padding-top:1px;
  padding-right:1px;
  padding-left:1px;
  mso-ignore:padding;
  color:black;
  font-size:12.0pt;
  font-weight:400;
  font-style:normal;
  text-decoration:none;
  font-family:Calibri, sans-serif;
  mso-font-charset:0;
  mso-number-format:General;
  text-align:center;
  vertical-align:bottom;
  mso-background-source:auto;
  mso-pattern:auto;
  white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Surat Pernyataan 2_23148" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=748 style='border-collapse:
 collapse;table-layout:fixed;width:562pt'>
 <col width=65 style='mso-width-source:userset;mso-width-alt:2280;width:49pt'>
 <col width=107 style='mso-width-source:userset;mso-width-alt:3746;width:81pt'>
 <col width=351 style='mso-width-source:userset;mso-width-alt:12241;width:263pt'>
 <col width=225 style='mso-width-source:userset;mso-width-alt:7866;width:169pt'>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 width=65 style='height:14.5pt;width:49pt'></td>
  <td class=xl1523148 width=107 style='width:81pt'></td>
  <td class=xl1523148 width=351 style='width:263pt'></td>
  <td class=xl1523148 width=225 style='width:169pt'></td>
 </tr>
 <tr height=28 style='height:21.0pt'>
  <td colspan=4 height=28 class=xl6523148 style='height:21.0pt'>SURAT
  PERNYATAAN</td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148 colspan=2>Yang bertanda tangan di bawah ini :</td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148>Nama</td>
  <td class=xl6323148>:<span style='mso-spacerun:yes'>  </span><?php echo $nama ?></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148>Tempat/Tgl. Lah<span style='display:none'>ir</span></td>
  <td class=xl6323148>:<span style='mso-spacerun:yes'> 
  </span><?php echo $tempatlahir.' / '.$tanggallahir ?></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148>Alamat</td>
  <td class=xl6323148>:<span style='mso-spacerun:yes'>  </span><?php echo $alamat ?></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148 colspan=3>Dengan ini memohon kepada Kepala Kantor
  Imigrasi Kelas II Non TPI Kediri agar kiranya mencetak</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148>nama saya</td>
  <td class=xl6323148>:<span style='mso-spacerun:yes'>  </span><?php echo $nama.' '.$namaayah.' '.$namakakek ?></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148 colspan=3>pada paspor yang akan saya gunakan untuk tujuan
  Ibadah Umroh/Haji pada tahun</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148 colspan=2>sebagai bahan pertimbangan berikut saya
  sampaikan data :</td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148>Nama Ayah Kan<span style='display:none'>dung</span></td>
  <td class=xl6323148>:<span style='mso-spacerun:yes'>  </span><?php echo $namaayah ?></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148>Nama Kakek Ka<span style='display:none'>ndung</span></td>
  <td class=xl6323148>:<span style='mso-spacerun:yes'>  </span><?php echo $namakakek ?></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148 colspan=3>Demikian Surat Pernyataan ini saya buat dengan
  sebenarnya, apabila di kemudian hari terdapat</td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148 colspan=2>kekeliruan saya bersedia diproses sesuai hukum
  yang berlaku.</td>
  <td class=xl1523148></td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl6623148>Kediri, <?php echo $tglpermohonan ?></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl6323148></td>
  <td class=xl1523148></td>
  <td class=xl6423148></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl6623148>Materai</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl1523148 style='height:15.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl6623148>Rp 10.000,-</td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl6423148></td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl6423148>( <?php echo $nama ?> )</td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl1523148 style='height:14.5pt'></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
  <td class=xl1523148></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=65 style='width:49pt'></td>
  <td width=107 style='width:81pt'></td>
  <td width=351 style='width:263pt'></td>
  <td width=225 style='width:169pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
<p style="page-break-after: always;">&nbsp;</p>
