<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="Suratpernyataanpenggantian_files/filelist.xml">
<style id="Surat Pernyataan 3_7019_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl157019
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl637019
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl647019
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Surat Pernyataan 3_7019" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=721 style='border-collapse:
 collapse;table-layout:fixed;width:541pt'>
 <col width=82 style='mso-width-source:userset;mso-width-alt:2862;width:62pt'>
 <col width=151 style='mso-width-source:userset;mso-width-alt:5259;width:113pt'>
 <col width=380 style='mso-width-source:userset;mso-width-alt:13265;width:285pt'>
 <col width=108 style='mso-width-source:userset;mso-width-alt:3770;width:81pt'>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl157019 width=82 style='height:14.5pt;width:62pt'></td>
  <td class=xl157019 width=151 style='width:113pt'></td>
  <td class=xl157019 width=380 style='width:285pt'></td>
  <td class=xl157019 width=108 style='width:81pt'></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2>Kediri, <?php echo $tglpermohonan; ?></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>Kepada Yth</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2>Kepala Kantor Imigrasi Kelas II Non TPI Kediri</td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2><span
  style='mso-spacerun:yes'>                   </span>Dengan hormat,</td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2>Yang bertanda tangan di bawah ini :</td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>Nama</td>
  <td class=xl157019>:<span style='mso-spacerun:yes'>  </span><?php echo $nama; ?></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>Tempat/Tgl. Lahir</td>
  <td class=xl157019>:<span style='mso-spacerun:yes'> 
  </span><?php echo $tempatlahir.' / '.$tanggallahir; ?></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>Pekerjaan</td>
  <td class=xl157019>:<span style='mso-spacerun:yes'>  </span><?php echo $pekerjaan; ?></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>Alamat</td>
  <td class=xl157019>:<span style='mso-spacerun:yes'>  </span><?php echo $alamat; ?></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2>adalah pemegang paspor Nomor Seri<span
  style='mso-spacerun:yes'>  </span>:<span style='mso-spacerun:yes'> 
  </span><strong><?php echo $nopaspor; ?></strong><span style='mso-spacerun:yes'>      </span>Nomor reg
  : <?php echo $noregister; ?></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=3>dengan ini memohon untuk meminjam paspor
  tersebut. Adapun paspor tersebut saya butuhkan</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>karena :</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2>1. Ada visa No.<span
  style='mso-spacerun:yes'>                                                          
  </span>Yang masih berlaku s/d</td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2>2. Ada bukti pernah mengajukan visa No.</td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2><span style='mso-spacerun:yes'>    </span>untuk
  pengurusan/kemudahan memohon visa lagi</td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=2>3. Untuk kemudahan/kelancaran dengan pihak bank
  di luar negeri</td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=3>4. Dokumen saya di luar negeri masih menggunakan
  data/nama yang ada di paspor lama</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=3>Apabila di kemudian hari ditemukan hal-hal yang
  tidak diinginkan, saya bersedia dituntut</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>di muka hukum.</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019 colspan=3><span style='mso-spacerun:yes'>                 
  </span>Demikian permohonan ini saya buat, atas kebijaksanaannya saya ucapkan
  terima</td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019>kasih.</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019><span style='mso-spacerun:yes'>           </span>Hormat
  saya,</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019><span style='mso-spacerun:yes'>              
  </span>Materai</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019><span style='mso-spacerun:yes'>             </span>Rp.
  10.000,-</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl637019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=21 style='height:15.5pt'>
  <td height=21 class=xl157019 style='height:15.5pt'></td>
  <td class=xl647019>( <?php echo $nama; ?> )</td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <tr height=19 style='height:14.5pt'>
  <td height=19 class=xl157019 style='height:14.5pt'></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
  <td class=xl157019></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=82 style='width:62pt'></td>
  <td width=151 style='width:113pt'></td>
  <td width=380 style='width:285pt'></td>
  <td width=108 style='width:81pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
/* <script type="text/javascript">
  window.print();
</script> */
</body>

</html>
<p style="page-break-after: always;">&nbsp;</p>
